import type { CourseItem, DataSourceType } from './data';
import ceshi from './ceshi.png';

export const listData: CourseItem[] = [
    {
        id: '7835u-uedejn2-792hs7481',
        KCMC: '美术',
        KCLX: '艺术类',
        KCSC: 45,
        KCFY: 4000,
        KCTP: ceshi,
        KCMS: '通过趣味的简单线描，色彩绘画...',
        KCZT: '待开课',
    },
    {
        id: '7835u-uedejn2-792hs7482',
        KCMC: '美术',
        KCLX: '艺术类',
        KCSC: 45,
        KCFY: 4000,
        KCTP: ceshi,
        KCMS: '通过趣味的简单线描，色彩绘画...',
        KCZT: '待开课',
    },
    {
        id: '7835u-uedejn2-792hs7483',
        KCMC: '美术',
        KCLX: '艺术类',
        KCSC: 45,
        KCFY: 4000,
        KCTP: ceshi,
        KCMS: '通过趣味的简单线描，色彩绘画...',
        KCZT: '待开课',
    },
    {
        id: '7835u-uedejn2-792hs7484',
        KCMC: '美术',
        KCLX: '艺术类',
        KCSC: 45,
        KCFY: 4000,
        KCTP: ceshi,
        KCMS: '通过趣味的简单线描，色彩绘画...',
        KCZT: '待开课',
    },
    {
        id: '7835u-uedejn2-792hs7485',
        KCMC: '美术',
        KCLX: '艺术类',
        KCSC: 45,
        KCFY: 4000,
        KCTP: ceshi,
        KCMS: '通过趣味的简单线描，色彩绘画...',
        KCZT: '待开课',
    },
    {
        id: '7835u-uedejn2-792hs7486',
        KCMC: '美术',
        KCLX: '艺术类',
        KCSC: 45,
        KCFY: 4000,
        KCTP: ceshi,
        KCMS: '通过趣味的简单线描，色彩绘画...',
        KCZT: '待开课',
    },
    {
        id: '7835u-uedejn2-792hs7487',
        KCMC: '美术',
        KCLX: '艺术类',
        KCSC: 45,
        KCFY: 4000,
        KCTP: ceshi,
        KCMS: '通过趣味的简单线描，色彩绘画...',
        KCZT: '待开课',
    },
    {
        id: '7835u-uedejn2-792hs7488',
        KCMC: '美术',
        KCLX: '艺术类',
        KCSC: 45,
        KCFY: 4000,
        KCTP: ceshi,
        KCMS: '通过趣味的简单线描，色彩绘画...',
        KCZT: '待开课',
    },
    {
        id: '7835u-uedejn2-792hs7489',
        KCMC: '美术',
        KCLX: '艺术类',
        KCSC: 45,
        KCFY: 4000,
        KCTP: ceshi,
        KCMS: '通过趣味的简单线描，色彩绘画...',
        KCZT: '待开课',
    },
    {
        id: '7835u-uedejn2-792hs7490',
        KCMC: '美术',
        KCLX: '艺术类',
        KCSC: 45,
        KCFY: 4000,
        KCTP: ceshi,
        KCMS: '通过趣味的简单线描，色彩绘画...',
        KCZT: '待开课',
    },
    {
        id: '7835u-uedejn2-792hs7491',
        KCMC: '美术',
        KCLX: '艺术类',
        KCSC: 45,
        KCFY: 4000,
        KCTP: ceshi,
        KCMS: '通过趣味的简单线描，色彩绘画...',
        KCZT: '待开课',
    },
    {
        id: '7835u-uedejn2-792hs7492',
        KCMC: '美术',
        KCLX: '艺术类',
        KCSC: 45,
        KCFY: 4000,
        KCTP: ceshi,
        KCMS: '通过趣味的简单线描，色彩绘画...',
        KCZT: '待开课',
    },
]

export const defaultData: DataSourceType[] = [
    {
        id: 624748507,
        decs: '这是艺术类',
        state: '艺术类',
    },
    {
        id: 624691221,
        decs: '这是文艺类',
        state: '文艺类',
    },
  ];