export const Data = {
  classCourseName: '初中部绘画艺术素描基础课',
  className: 'B班',
  classTotal: '12',
  classCurrent: '5',
  shouldArrive: '32',
  realTo: '30',
  leave: '2',
  absent: '0',
  studentList: [
    {
      name: '张三',
      class: '三（2）班',
      isLeave: '是',
      isRealTo: '缺席',
      id: 1,
    },
    {
      name: '李四',
      class: '三（2）班',
      isLeave: '是',
      isRealTo: '缺席',
      id: 2,
    },
    {
      name: '王五',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 3,
    },
    {
      name: '赵六',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 4,
    },
    {
      name: '赵七',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 5,
    },
    {
      name: '周八',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 6,
    },
    {
      name: '吴九',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 7,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 8,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 9,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 10,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 11,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 12,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 13,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 14,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 15,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 16,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 17,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 18,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 19,
    },
    {
      name: '郑十一',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 20,
    },
    {
      name: '刘进',
      class: '三（2）班',
      isLeave: '否',
      isRealTo: '到课',
      id: 21,
    },
  ],
};
